### ISSUE TITLE
wz-cancel and canexit attributes for wzStep are not working

### ISSUE THREAD

**Issue by C00per** [mgonto/angular-wizard#106]
Hi,
It is strange that these attributes are not working.
"wz-cancel" always go on previous step
"canexit " is not executed. I tried to set to "false" - but no luck.

Actually I want to restrict go to the previous steps on the last step. Also on the last step I want to add a button to restart wizard (i.e. start from the fist step and mark all others steps as incompleted, as after the page was loaded).

**Comment by jacobscarter** [comment]
@C00per you are correct, cancel was calling the same function as previous.  Since the documentation says cancel takes you to the first step I changed it to do so with version 0.5.2

In regards to canexit not working, we have unit tests showing it works as well as my personal tests, can you post a Fiddle of your code where it does not work.

You can restrict going to a previous step on the last step several ways:

*  Don't put a previous button
*  Store the currentStep in the context object and put a canenter check on the second to last step making sure that you are not coming from the last step
*  Put a canexit check on the last step making sure the step you are traveling to is not the previous step

Having the cancel button set all the other steps to incomplete is something I want to get more feedback on from other users before implementing.

Thanks.

**Comment by C00per** [comment]
@jacobscarter 
Thank you for your answers. 
1) From my point of view it is correct to set other steps to incoplete after cancel. I'll add button with ```wz-cancel``` to restart wizard for uploading another file if the current file has errors or in the last step. Anyway is there any another way to do it? I was thinking about toggling ```ng-if``` directive as a workaround.
2) It was not obvious for me that ```canexit``` checks transition only to the next step but no to the previous. So it is working well. 
Anyway I did the second solution, that you proposed, in the [fiddle] (https://jsfiddle.net/mnch2gt3/3/). It will be great to replace ```WizardHandler.wizard("wzName").goTo(0);``` with ```wz-cancel``` for the restart button as I alredy said. Also it may be a good idea not change the cursor when it hoovers over disabled (```canenter="false"```) steps (i.e. there should not to be href for them).

**Comment by jacobscarter** [comment]
Reset button scheduled for next release. See #142

**Comment by jacobscarter** [comment]
Added and will be in next push
