### ISSUE TITLE
doble invoke

### ISSUE THREAD

**Issue by Inteligov** [mgonto/angular-wizard#113]
when use canexit in 'wz-step' , the associated function is executed twice

**Comment by brunnot** [comment]
I found the problem, but no solution yet.
The problem is that the component calls 2 times the same function, one to check if it's a PROMISE and another to check if it's BOOLEAN.

If you just use return as PROMISE will work fine.

canExit = step.canexit($scope.context);
if(angular.isFunction(canExit.then)){
    ....
}
 return step.canexit($scope.context) === true;

tks
Brunno

**Comment by MotherCake** [comment]
I'm facing the same problem. But I'm using PROMISE and get this error "Cannot read property 'then' of undefined" at the same lines brunnot descriped. Is there any fix or workaround?

**Comment by j-hernandez** [comment]
@MotherCake 

This is only a band-aid - if you review @brunnot's comment, note the line: 

````
    if(angular.isFunction(canExit.then)){
````

Change that line to 
````
    if(angular.isFunction(canExit)){
`````

It doesn't solve the double invoke, but it does get around the Cannot read property issue. If I have some time this week I'll debug further and see if I can submit a patch. Up against a deadline and only just came across this bug so for now, just making it work.

**Comment by jacobscarter** [comment]
Working on this from other ticket

**Comment by jacobscarter** [comment]
corrected and in next release
