### ISSUE TITLE
Reset the wizard programatically

### ISSUE THREAD

**Issue by xvitcoder** [mgonto/angular-wizard#121]
Nice wizard, but how to reset the wizard programmatically?
It would be nice to have WizardHandler.wizard().reset() function that will reset the wizard and all its' values.
It would be very helpful when using wizards in a Bootstrap Modal Dialog. When the user press cancel button, the dialog with the wizard is closed, but there is no way to reset the entered values and allow opening the dialog one more time with the fresh wizard values.

**Comment by jacobscarter** [comment]
Hi @xvitcoder.  If I understand your question correctly, I don't think this is the responsibility of the wizard.  The wizard is meant to allow you to create steps that can be validated and navigated.  There is no restriction to the data that you collect or provide within each step.  The wizard is also not inherently aware of the data in each step.

If you want to reset data you would be able to do that from your controller because you know what models you need to reset, where as the wizard does not.

**Comment by joshting** [comment]
I also support xvitcoder with regards to having a reset.  However, I come from slightly a different point of view.  Yes, its not the responsibility of the wizard to manipulate the data in each step.  By reset here, I mean going back to the first step and as if none of the following steps have been visited.  Currently, using cancel does not reset to the behaviour when the wizard first started. User can still click can go to all the visited steps.

We need a reset in the situation when the same wizard needs to be repeated to collect multiples of same set of data on the same view.
