### ISSUE TITLE
How to call a function on a specific step?

### ISSUE THREAD

**Issue by talal89** [mgonto/angular-wizard#192]
Hi, How can i call a function on a specific step? 

Lets say i have 4 steps and in every step there is a function which alerts a message and displays the step number.

Or lets say i have a function i want to execute on step 2 and step 4. How can i achieve that?

**Comment by jacobscarter** [comment]
There are several ways to do this:

* Have a unique controller per step and add the function to said controller for said step
* Put a $watch statement in the controller for your wizard that watches the currentStep and fires a function when currentStep === X
* Instead of using wz-next on your step button make a custom function within ng-click and call the function you want and then call wz-next from within that function.
